version = 1

[*]
device = CUDA0
jinja = true
fa = on
ngl = 999
reasoning = auto
parallel = 1

kv-offload = true
;mlock = true
;no-mmap = true

temp = 0.6

;---------------------- Qwen --------------------------------------


[unsloth/Qwen3.6-35B-A3B-GGUF:Q6_K_XL]
;override-kv = qwen35moe.expert_used_count=int:8

chat-template-kwargs = {"preserve_thinking": true}
no-mmproj-offload = true
reasoning-budget = 8096
reasoning-budget-message = Enough thinking, let's jump into it.

ctx-size = 100000
ctk = q8_0
ctv = q8_0

moe-hot-cache-max-mib = -1
moe-hot-cache = /home/adrian/llama.exp/qwen_profile
moe-hot-cache-update-rate = 0.25
moe-hot-cache-weighting = pressure
moe-hot-cache-qwen-layer-curve =  0.7
moe-hot-cache-pp-reduce-merge = auto

cpu-moe = true
;override-tensor = blk\.(0|1|2|3|4|5|6|40)\.ffn_(up|down|gate|gate_up)_(ch|)exps\.weight=CUDA0,blk\.(8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|7)\.ffn_(up|down|gate|gate_up)_(ch|)exps\.weight=CPU

[unsloth/Qwen3-Coder-Next-GGUF:IQ4_NL]
;override-kv = qwen35moe.expert_used_count=int:8

chat-template-kwargs = {"preserve_thinking": true}
no-mmproj-offload = true
reasoning-budget = 8096
reasoning-budget-message = Enough thinking, let's jump into it.

ctx-size = 100000

moe-hot-cache-max-mib = -1
moe-hot-cache = /home/adrian/llama.exp/coder
moe-hot-cache-update-rate = 0.25
moe-hot-cache-weighting = pressure
moe-hot-cache-qwen-layer-curve =  0.7
moe-hot-cache-pp-reduce-merge = auto

cpu-moe = true

; ------------------------ GEMMA --------------------------------
[unsloth/gemma-4-E4B-it-GGUF:Q6_K_XL]
parallel = 1
no-mmproj-offload = false
ngl = 99
ctx-size = 100000

[unsloth/gemma-4-26B-A4B-it-GGUF:Q6_K_XL]
cpu-moe = true
no-mmproj-offload = true
ngl = 999
ctx-size = 100000
ctv = q8_0
ctk = q8_0
moe-hot-cache-max-mib = -1
moe-hot-cache = /home/adrian/llama.exp/gemma4
moe-hot-cache-update-rate = 0.25
moe-hot-cache-auto-reserve-mib = 650
moe-hot-cache-pp-reduce-merge = auto


; ------------------------ other --------------------------------
